### ISSUE TITLE
Segmentation fault on WRT1900ACSv2 running Debian 10

### ISSUE THREAD

**Issue by bmalnersic** [commonism/iptables-trace#5]
Running without any options returns help, however running with some options results in segmentation fault:
`# python3 iptables-trace.py  -s 10.9.8.4 --limit`
`Namespace(bpf='', chain=['OUTPUT', 'PREROUTING'], clear_chain=False, destination=None, limit=True, protocol=None, source='10.9.8.4', xmark_mask='0x800001ff')`
`Segmentation fault`
The application works on RPi4 (8GB memory)  with 32-bit Debian 11. Maybe the issue is with system having only 512MB RAM?

**Comment by commonism** [comment]
Debugging on embedded systems …
You'll be better of using iptables-over-nftables and xtables-monitor --trace instead of iptables-legacy & iptables-trace.py

**Comment by bmalnersic** [comment]
I would not say it is an embedded system. It is running McDebian, which is actually Debian 10 (Buster) for armv7l systems, with kernel 5.6.14. Packages are installed from the regular Debian repositories.
Indeed, using xtables-monitor + TRACE rules seems the choice here, as it works just fine. Thank you for a quick replay! As it says on the home page of the project, if nftables are used (and I am using those) then xtables-monitor is the ways to go...:)
